### ISSUE TITLE
Timed out when not moving for some time

### ISSUE THREAD

**Issue by SlenkyDev** [LOOHP/Limbo#30]
Hi there,
Players get timed out if they do not interact with the server in a while.

Please fix this, otherwise we can't use this. (afk server)

**Comment by SlenkyDev** [comment]
> Probably an duplicate with Issue #29

nah

**Comment by LOOHP** [comment]
Should be fixed in 0.6.8-ALPHA

**Comment by amgno** [comment]
still happening when connecting with 1.8.9 and using Velocity ViaVersion
